Entity classes
sireclifford/oop-school-libray pull request #1
Opened 2022-09-27 22:14 UTC by sireclifford

- Implement classes and objects in Ruby.
- Implement encapsulation and inheritance with Ruby.
- Run a program using the command line.
- Create person class
- Create student class
- Create teacher class

2022-09-27 22:26 UTC, addod19 requested changes
### Hi @sireclifford, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [ ] README is descriptive :fireworks: 
- [ ] Git-flow followed :rocket: 
- [ ] PR is detailed with project tasks :100: 
- [ ] Individual files for teacher, person, student present :1st_place_medal: 
- [ ] Rubys' OOP inheritance implemented :man_technologist: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing all commit messages :smile: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 22:26 UTC, addod19 commented on person.rb
> +  attr_reader :id, :name, :age
- [ ] It would be better if we set the getter and setter for our `name` and `age`. Since we are not only reading the values but also writing

2022-09-27 22:26 UTC, addod19 commented on person.rb
> +  end
- [ ] It would be better if our method `is_of_age` is a private method. So that it can not be accessed by any of the classes

2022-09-28 06:30 UTC, phelian23 approved these changes
Hi @sireclifford,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good descriptive PR 👍
✅ Good commit messages 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 07:41 UTC, merged